global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:3000']
    metrics_path: /metrics

  - job_name: 'auth-service'
    static_configs:
      - targets: ['host.docker.internal:5001']
    metrics_path: /metrics

  - job_name: 'payment-service'
    static_configs:
      - targets: ['host.docker.internal:8081']
    metrics_path: /actuator/prometheus

  - job_name: 'exchange-rate-service'
    static_configs:
      - targets: ['host.docker.internal:8082']
    metrics_path: /metrics

  - job_name: 'settlement-service'
    static_configs:
      - targets: ['host.docker.internal:8083']
    metrics_path: /metrics

  - job_name: 'notification-service'
    static_configs:
      - targets: ['host.docker.internal:3002']
    metrics_path: /metrics
